# Generated by Django 4.1.3 on 2022-11-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acno', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('aadhar', models.PositiveBigIntegerField()),
                ('mobile', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.PositiveIntegerField()),
                ('actype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeManagement.accounttype')),
            ],
        ),
    ]
